version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "build.gradle" }}
            - v1-deps-
      - run:
          name: Check spotless
          command: ./gradlew spotlessCheck
      - run:
          name: Run tests
          command: ./gradlew clean test
      - run:
          name: Save test results
          command: |
            mkdir test-results
            find . -type f -regex "./build/test-results/.*/.*xml" -exec cp {} test-results \;
          when: always
      - store_test_results:
          path: ./test-results
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-deps-{{ checksum "build.gradle" }}

workflows:
  version: 2
  push-tests:
    jobs:
      - test
